/*
Project: Retail Sales Analytics using SQL Server

Description:
This project performs end-to-end retail sales analysis using SQL.

Steps included:
1. Data exploration
2. Data cleaning and validation
3. Star schema data modeling
4. KPI calculations
5. Advanced analytical queries using window functions

Key KPIs:
- Total Sales
- Monthly Sales Trend
- Average Order Value
- Sales by Region
- Top Customers
- Top Products
- Year-over-Year Growth
- Running Sales Total
- Sales Contribution %

Tools Used:
SQL Server
*/
--CREATING THE DATABASE
Create Database Retail_Sales_Analytics

USE Retail_Sales_Analytics
--Preview the raw data
Select top 10 * from Sales_data

--Check Toatl Records
Select count(*) as Total_row_count from Sales_data

--check column data types
EXEC sp_help 'sales_data';

--TRANSFORM (Data Cleaning)

select
sum(case when[ORDER_ID] is null then 1 else 0 END)AS NULL_ORDER_ID,
SUM(CASE WHEN[CUSTOMER_ID] IS NULL THEN 1 ELSE 0 END )AS NULL_CUSTOMER_ID,
SUM (CASE WHEN SALES IS NULL THEN 1 ELSE 0 END)AS NULL_SALES
FROM SALES_DATA
 
--Identify duplicate order–product combinations

SELECT
ORDER_ID,PRODUCT_ID, COUNT(*) AS DUPLICATE_COUNT 
FROM SALES_DATA
GROUP BY ORDER_ID,PRODUCT_ID
HAVING COUNT(*)>1;


--Validate date values

SELECT ORDER_DATE,SHIP_DATE FROM Sales_data
WHERE TRY_CONVERT(DATE,ORDER_DATE,103)IS NULL OR
 TRY_CONVERT(DATE,SHIP_DATE,103)IS NULL;

--CONVERT ORDER DATE AND SHIFT DATE

UPDATE Sales_data
SET Order_Date= TRY_CONVERT(DATE,ORDER_DATE,103),
Ship_Date= TRY_CONVERT (DATE,SHIP_DATE,103)

--CHECK INVALID SALES VALUE
SELECT * FROM Sales_data
WHERE SALES<0

--STANDARDIZE TEXT COLUMN

UPDATE Sales_data
SET CITY=UPPER(CITY),
STATE=UPPER(STATE),
CATEGORY=UPPER(CATEGORY),
SUB_CATEGORY=UPPER(SUB_CATEGORY),
SEGMENT=UPPER(SEGMENT),
REGION=UPPER(REGION)

--LOAD STAR SCHEMA DESIGN

--DIMENSION TABLES 
--CUSTOMER DIMENSION

SELECT DISTINCT 
CUSTOMER_ID,Customer_Name,
Segment,Country,City,STATE,
Postal_Code,Region INTO DIM_CUSTOMERS
FROM Sales_data

--PRODUCT DIMENSION

SELECT DISTINCT 
PRODUCT_ID,
CATEGORY,
PRODUCT_NAME,
SUB_CATEGORY INTO DIM_PRODUCTS
FROM Sales_data

--FACT TABLE
--SALES FACT TABLE
SELECT Row_ID,Order_ID,
Order_Date,
Ship_Date,Ship_Mode,
Customer_ID,Product_ID ,SALES
INTO FACT_SALES
FROM Sales_data


--ROW COUNT VALIDATION

SELECT
(SELECT COUNT(*) FROM Sales_data)AS ROW_COUNT,
(SELECT COUNT(*) FROM Fact_sales) AS FACT_COUNT;

--JOIN CHECK

SELECT TOP 10 F.ORDER_ID,C.CUSTOMER_NAME,P.PRODUCT_NAME,F.SALES
FROM FACT_SALES F 
JOIN DIM_CUSTOMERS C ON F.Customer_ID=C.Customer_ID
JOIN DIM_PRODUCTS P ON F.Product_ID=P.Product_ID;


--Data Validation & Quality Checks
--Row count validation
SELECT
    (SELECT COUNT(*) FROM sales_data) AS raw_rows,
    (SELECT COUNT(*) FROM fact_sales) AS fact_rows;

--Null check in fact table
SELECT
    SUM(CASE WHEN Sales IS NULL THEN 1 ELSE 0 END) AS null_sales
FROM fact_sales;

--Core KPIs for our data:

--1.Total Sales

--2.Monthly Sales Trend

--3.Average Order Value (AOV)

--4.Sales by Region

--5.Sales by Category & Sub-Category

--6.Top Customers

--7.Top Products

--8.TOP 5 PRODUCTS PER REGION

--9.YEAR-OVER-YEAR SALES GROWTH

--10.RUNNING SALES TOTAL(CUMULATIVE SALES)

--11.SALES CONTRIBUTION %


--STEP 2: Exploratory Data Analysis

--1.Total Sales
SELECT floor(SUM(SALES)) AS TOTAL_SALES 
FROM FACT_SALES

--2.Monthly Sales Trend
SELECT YEAR(ORDER_DATE) AS YEAR,
 MONTH(ORDER_DATE) AS MONTH,
 SUM(SALES) AS MONTHLY_SALES 
 FROM FACT_SALES
 GROUP BY YEAR(ORDER_DATE),MONTH(Order_Date)
 ORDER BY YEAR,MONTH

--3.Average Order Value (AOV)

 SELECT SUM(SALES)/COUNT(DISTINCT(ORDER_ID)) AS AVERAGE_ORDER_VALUE 
 FROM FACT_SALES

--4.SALES BY REGION

SELECT 
C.REGION,
SUM(F.SALES) AS TOTAL_SALES 
FROM FACT_SALES F
JOIN DIM_CUSTOMERS C
ON F.CUSTOMER_ID=C.CUSTOMER_ID
GROUP BY C.REGION
ORDER BY TOTAL_SALES DESC


--5.SALES BY CATEGORY & SUB-CATEGORY
SELECT P.CATEGORY,P.SUB_CATEGORY,
SUM(F.SALES) AS TOTAL_SALES 
FROM FACT_SALES F 
JOIN DIM_PRODUCTS P 
ON F.Product_ID=P.Product_ID
GROUP BY P.Sub_Category,P.Category
ORDER BY TOTAL_SALES DESC


SELECT * FROM DIM_PRODUCTS
SELECT * FROM FACT_SALES


--6.TOP CUSTOMERS (customers who generate highest revenue.)
SELECT  TOP 10 D.CUSTOMER_NAME,
SUM(F.SALES) AS HIGHEST_REVENUE
FROM FACT_SALES F
JOIN DIM_CUSTOMERS D
ON D.Customer_ID=F.Customer_ID
GROUP BY D.Customer_Name
ORDER BY HIGHEST_REVENUE DESC


--7.TOP PRODUCTS (products generating maximum revenue.)

SELECT TOP 10 
P.PRODUCT_NAME,
SUM(F.SALES)TOP_SALES
FROM FACT_SALESSS F
JOIN DIM_PRODUCTS P
ON P.PRODUCT_ID=F.Product_ID
GROUP BY Product_NAME
ORDER BY TOP_SALES DESC

---8.TOP 5 PRODUCTS PER REGION
--This shows best selling products in each region.

SELECT * FROM (
SELECT C.REGION,
P.PRODUCT_NAME,
SUM(F.SALES) AS TOTAL_SALES,
RANK() OVER(PARTITION BY C.REGION 
ORDER BY SUM(F.SALES) DESC) AS RANKING
FROM FACT_SALES F
JOIN DIM_CUSTOMERS C
   ON F.Customer_ID=C.Customer_ID
JOIN DIM_PRODUCTS P
   ON F.Product_ID=P.PRODUCT_ID
GROUP BY C.REGION,P.PRODUCT_NAME
)A
WHERE RANKING<=5;

--9.YEAR-OVER-YEAR SALES GROWTH

SELECT 
YEAR(ORDER_DATE) AS YEAR,
FLOOR(SUM(SALES)) AS YEARLY_SALES,
LAG(FLOOR(SUM(SALES))) OVER(ORDER BY YEAR(ORDER_DATE)) AS PREVIOUS_YEAR_SALES,
FLOOR(SUM(SALES))-LAG(FLOOR(SUM(SALES))) OVER(ORDER BY YEAR(ORDER_DATE)) AS SALES_GROWTH
FROM FACT_SALES
GROUP BY YEAR(ORDER_DATE);


--9.CUSTOMER LIFETIME VALUE WITH >100000
SELECT P.CUSTOMER_NAME,
FLOOR(SUM(F.SALES)) AS CUSTOMER_LIFETIME_VALUE
FROM FACT_SALES F
JOIN DIM_CUSTOMERS P
ON P.Customer_ID=F.Customer_ID
GROUP BY Customer_Name
HAVING SUM(SALES)>100000
ORDER BY CUSTOMER_LIFETIME_VALUE DESC


--10.RUNNING SALES TOTAL(CUMULATIVE SALES)

SELECT ORDER_DATE,
SUM(SALES) AS DAILY_SALES,
SUM(SUM(SALES)) OVER (ORDER BY ORDER_DATE) AS RUNNING_TOTAL
FROM FACT_SALES
GROUP BY ORDER_DATE
ORDER BY ORDER_DATE

--11.SALES CONTRIBUTION %
SELECT 
P.CATEGORY,FLOOR(SUM(F.SALES)) AS TOTAL_SALES,
SUM(F.SALES)*100.0/SUM(SUM(F.SALES)) OVER() AS SALES_PERCENTAGE
FROM FACT_SALES F
JOIN DIM_PRODUCTS P
ON F.PRODUCT_ID=P.PRODUCT_ID 
GROUP BY P.CATEGORY


